model_list:
  - model_name: glm-5.1
    litellm_params:
      model: openai/glm-5.1
      api_key: os.environ/ZAI_API_KEY
      api_base: https://api.z.ai/api/coding/paas/v4
  - model_name: glm-5-turbo
    litellm_params:
      model: openai/glm-5-turbo
      api_key: os.environ/ZAI_API_KEY
      api_base: https://api.z.ai/api/coding/paas/v4
  - model_name: glm-5
    litellm_params:
      model: openai/glm-5
      api_key: os.environ/ZAI_API_KEY
      api_base: https://api.z.ai/api/coding/paas/v4
  - model_name: glm-4.7
    litellm_params:
      model: openai/glm-4.7
      api_key: os.environ/ZAI_API_KEY
      api_base: https://api.z.ai/api/coding/paas/v4
  - model_name: glm-4.5-air
    litellm_params:
      model: openai/glm-4.5-air
      api_key: os.environ/ZAI_API_KEY
      api_base: https://api.z.ai/api/coding/paas/v4
  - model_name: qwen3-vl-4b
    litellm_params:
      model: openai/qwen3-vl-4b
      api_base: http://eve:58081/v1
      api_key: sk-dummy
  - model_name: qwen3.5-4b
    litellm_params:
      model: openai/qwen3.5-4b
      api_base: http://girl:58081/v1
      api_key: sk-dummy


general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
