apiVersion: ENC[AES256_GCM,data:mMQ=,iv:Tls4gRlGI4N1/ryFUXNTHKXncfR8qApbQP8pOfdsCD8=,tag:WKM0WsqEofmDyjM/+Pt6AQ==,type:str]
kind: ENC[AES256_GCM,data:yxTEPBrt,iv:JIR8RamhisLcsaP8ACxWcLj+Ek9n3e6SgZOsPv9sxek=,tag:wZ0+5HdZPXtdynrACUC7eA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:pAOSJUiNi0b/u/2Nm5iz,iv:tqx6BY1yleBCXyk4prleohV/jMSBCajtPNCRln2oYmU=,tag:glys+SmATN11grjuEQAPfA==,type:str]
    namespace: ENC[AES256_GCM,data:nn81fg==,iv:gUROrOuiZFndbnu1TgGL0b/OnhemO58E/OmvRAZw7U0=,tag:3GNqpqU0l3zKTnp8vxU+/g==,type:str]
type: ENC[AES256_GCM,data:PgXxOKrB,iv:TngA7iU40UZzFpGdvTcxuOvJ1CqGVsyzmsiMCmfy/oI=,tag:btP4dIS9E7krywiGZuVFxg==,type:str]
stringData:
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:8JE6kSKaQzbDr7LO8bbWC2aliA==,iv:00aXW+YskTIQEYbOlCcchjHrbgKI5ehYgVJStlGe04I=,tag:dx3UeBSSnXcYV6aWlcX+ZQ==,type:str]
    VLLM_API_KEY: ENC[AES256_GCM,data:M8N7Kbv1fVLaoC88flmb5BXZfEE61B3nUX/4JkZPf+YEI9xv6oW5BJTaYSLUgdU6,iv:CxgFIahfKf/6xY4MQf8AjYYVRK0W1FmQt9efRAOHiMo=,tag:XsQQgDO5gwk2YyVl13YUDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZKzBlbDRGS0lkN0F4b0xU
            RUpLTVUwY294TDhMY21WRUZmV1ZQMGc2akVvCmR4aVZ3L0laaG9ySDgwOTBOZ1U3
            djlyWkZzV1c2N2E4REZ6K1huTmpDbDAKLS0tIFpXTm5lS3FKZEhidW1HVWNPZjFS
            T2FOek94ODZhdUN1bmFlRGhaWVQvUm8K338JFmDP6AIGtr0xE0ALMS+OEJFdC4uV
            2gDmKIwTVSDsH4Q1p+aI/ggo5vj1BgqaETh4kDW7nIutYmd1dkjy+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qw643dna4spaup6sr5ap0jf039ncjd54e8ekvrfy6p6x96ys2y4qn5vcsy
    lastmodified: "2026-09-03T11:11:50Z"
    mac: ENC[AES256_GCM,data:vEtzX+d1Gp0Txj7RC3kXzNdx2ckGyS0NUdq71Rduse+zMXSqgixmXS9LQtgo4f/nDrs7K1dWALeQK58Xyb0QNLyXO5F95SLaIDbpRmtdtfQwxNPb5wiVUS3hyOSOlIyyGk8YhlbNV7GCeXHZ+j4K1MBolO6vm8gLZHHZfYKTWig=,iv:SpTrS1Ca73ZCXmy7I3F6jMk6oxFhOohUrPlOPI0UiDM=,tag:GcG8tUodyfxNW8OZg17M+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
